spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://8.130.66.194:13306/gulimall_ums?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    driverClassName: com.mysql.cj.jdbc.Driver
mybatis-plus:
  mapper-location: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
server:
  port: 8000